# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_ram/axi_ram.xci
# IP: The module: 'axi_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_ram/axi_ram.xci
# IP: The module: 'axi_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
