# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NSCSCC2019/NSCSCC2019_TEST/axi_perf_test/test_project/template/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
